#!/usr/bin/env python3
"""Render the homebrew tap formula (Formula/cuttle.rb) from uv.lock.

The formula installs the released sdist into a keg virtualenv; every runtime
dependency is pinned to the exact sdist uv.lock resolved. Only [project.dependencies]
is walked - the container-only `server` group stays out of the formula, which is
also why no dep here needs a rust toolchain to build from sdist. Stdlib only - CI
runs it with plain python3.
"""

import argparse
import hashlib
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

TEMPLATE = """\
# typed: false
# frozen_string_literal: true

# Generated by glim-sh/cuttle scripts/render-homebrew-formula.py - do not edit.
class Cuttle < Formula
  include Language::Python::Virtualenv

  desc "Host CLI for the cuttle stealth-Chromium CDP farm"
  homepage "https://github.com/glim-sh/cuttle"
  url "https://github.com/glim-sh/cuttle/releases/download/v@VERSION@/cuttle_browser-@VERSION@.tar.gz"
  sha256 "@SHA256@"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_releases
    regex(/^v?(\\d+(?:\\.\\d+)+)$/i)
  end

  depends_on "python@3.12"

@RESOURCES@

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "usage: cuttle", shell_output("#{bin}/cuttle --help")
  end
end
"""


def runtime_closure(lock: dict) -> list[str]:
    pkgs = {p["name"]: p for p in lock["package"]}
    closure: set[str] = set()
    queue = [d["name"] for d in pkgs["cuttle-browser"].get("dependencies", [])]
    while queue:
        name = queue.pop()
        if name in closure:
            continue
        closure.add(name)
        queue += [d["name"] for d in pkgs[name].get("dependencies", [])]
    return sorted(closure)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", required=True)
    ap.add_argument("--sdist", required=True, type=Path, help="released sdist, for its sha256")
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    lock = tomllib.loads((ROOT / "uv.lock").read_text())
    pkgs = {p["name"]: p for p in lock["package"]}

    resources = []
    for name in runtime_closure(lock):
        sdist = pkgs[name].get("sdist")
        if sdist is None:
            print(f"error: {name} has no sdist in uv.lock (wheel-only?)", file=sys.stderr)
            return 1
        sha = sdist["hash"].removeprefix("sha256:")
        resources.append(
            f'  resource "{name}" do\n    url "{sdist["url"]}"\n    sha256 "{sha}"\n  end'
        )

    formula = (
        TEMPLATE.replace("@VERSION@", args.version)
        .replace("@SHA256@", hashlib.sha256(args.sdist.read_bytes()).hexdigest())
        .replace("@RESOURCES@", "\n\n".join(resources))
    )
    args.out.write_text(formula)
    return 0


if __name__ == "__main__":
    sys.exit(main())
